### ISSUE TITLE
Uncertainty-aware Accuracy (UAcc) Formula

### ISSUE THREAD

**Issue by chenxwh** [smartyfh/LLM-Uncertainty-Bench#2]
Thanks for sharing the work addressing the uncertainty of LLMs!

I do have a question regarding the UAcc Formula, what is the rationale for using `square root` of the option set? I did not seem to find it explained in the paper.

Thank you!

**Comment by smartyfh** [comment]
> Thanks for sharing the work addressing the uncertainty of LLMs!
> 
> I do have a question regarding the UAcc Formula, what is the rationale for using `square root` of the option set? I did not seem to find it explained in the paper.
> 
> Thank you!

Hi Chenxi,

Thanks for your interest in our work. The incorporation of the square root allows UAcc to be smaller or larger than Acc. It should be noted that SS is always greater than or equal to 1, that's why we added the square root term.

 Thanks,
